### ISSUE TITLE
Upload real sources

### ISSUE THREAD

**Issue by davelab6** [noirblancrouge/YoungSerif#3]
In https://github.com/uplaod/YoungSerif/blob/master/sources/YoungSerif-Regular.ufo/metainfo.plist#L6 I see that the project is developed with Glyphs. 

With https://github.com/googlei18n/fontmake it is now an open format, so please checkin your real/actual sources :) 

I'd also be very happy if you could read and suggest improvements to https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md

**Comment by noirblancrouge** [comment]
Better late than never, we made the fontmake move.

Thanks !
